import Card1 from "./assets/cate1.png";
import Card2 from "./assets/cate2.png";
import Card3 from "./assets/cate3.png";
import Card4 from "./assets/cate4.png";

export const Data = [
  {
    id: 1,
    img: Card1,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 2,
    img: Card2,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen ",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 3,
    img: Card3,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 4,
    img: Card4,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 5,
    img: Card4,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 6,
    img: Card4,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 7,
    img: Card4,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
  {
    id: 8,
    img: Card4,
    info: "Tawheed",
    time: "3 Months",
    name: "Kitaabut Tawheed bySheikh Uthaymeen",
    desc: "Lorem Ipsum is simplythe printing and typesetting  Lorem Ipsum has been the...",
    teacher: "Sh. Al-Madkhali",
    price: "$Free",
  },
];
